services:
  db:
    image: postgres:15
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - "${APP_PORT}:8080"
    command: mvn spring-boot:run
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      APP_PORT: 8080
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    depends_on:
      db:
        condition: service_started

volumes:
  db_data:
    name: sepm_project_db_data