spring:
  application:
    name: project
  docker:
    compose:
      enabled: false
  datasource:
    url: ${DB_URL:${DATABASE_URL:}}
    username: ${DB_USER:${PGUSER:}}
    password: ${DB_PASSWORD:${PGPASSWORD:}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: ${THYMELEAF_CACHE:true}

server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${PORT:8080}

admin:
  email: ${ADMIN_EMAIL:}
  password: ${ADMIN_PASSWORD:}
