package com.example.project.notification.event;

public enum NotificationEventType {
    EXCHANGE_REQUEST_SENT,
    EXCHANGE_ACCEPTED,
    EXCHANGE_REJECTED,
    DELIVERY_CREATED,
    DELIVERY_ASSIGNED,
    FIRST_PICKUP_APPROACHING,
    PICKUP_STARTED,
    SECOND_PICKUP_APPROACHING,
    BOOK_PICKED,
    FINAL_DELIVERY_APPROACHING,
    DELIVERY_COMPLETED,
    SYSTEM_ANNOUNCEMENT
}
